import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Plus, Trash2, Eye, Loader2 } from "lucide-react";
import { invoke } from "@tauri-apps/api/core";
import { useWizardStore } from "@/store/wizardStore";
import { useServerStore } from "@/store/serverStore";
import type { EnvVar } from "@/store/wizardStore";

// Default ENV vars per service (host auto-filled)
const SERVICE_DEFAULTS: Record<string, (host: string) => EnvVar[]> = {
  minio: (h) => [
    { key: "MINIO_ROOT_USER", value: "minioadmin" },
    { key: "MINIO_ROOT_PASSWORD", value: "" },
    { key: "MINIO_HOST", value: h },
    { key: "MINIO_PORT", value: "9000" },
    { key: "MINIO_CONSOLE_PORT", value: "9001" },
  ],
  rabbitmq: (h) => [
    { key: "RABBITMQ_DEFAULT_USER", value: "admin" },
    { key: "RABBITMQ_DEFAULT_PASS", value: "" },
    { key: "RABBITMQ_HOST", value: h },
    { key: "RABBITMQ_PORT", value: "5672" },
    { key: "RABBITMQ_MANAGEMENT_PORT", value: "15672" },
  ],
  keycloak: (h) => [
    { key: "KEYCLOAK_ADMIN", value: "admin" },
    { key: "KEYCLOAK_ADMIN_PASSWORD", value: "" },
    { key: "KC_HOST", value: h },
    { key: "KC_PORT", value: "8080" },
  ],
  redis: (h) => [
    { key: "REDIS_HOST", value: h },
    { key: "REDIS_PORT", value: "6379" },
    { key: "REDIS_PASSWORD", value: "" },
  ],
  elasticsearch: (h) => [
    { key: "ES_HOST", value: h },
    { key: "ES_PORT", value: "9200" },
    { key: "ES_USERNAME", value: "elastic" },
    { key: "ES_PASSWORD", value: "" },
  ],
  grafana: (h) => [
    { key: "GF_SECURITY_ADMIN_USER", value: "admin" },
    { key: "GF_SECURITY_ADMIN_PASSWORD", value: "" },
    { key: "GF_HOST", value: h },
    { key: "GF_PORT", value: "3000" },
  ],
  prometheus: (h) => [
    { key: "PROMETHEUS_HOST", value: h },
    { key: "PROMETHEUS_PORT", value: "9090" },
  ],
};

function buildEnvContent(
  services: { name: string; displayName: string }[],
  envVars: Record<string, EnvVar[]>
): string {
  const lines: string[] = ["# vms.env — generated by VMS Deploy Tools", ""];
  for (const svc of services) {
    const vars = envVars[svc.name] ?? [];
    if (vars.length === 0) continue;
    lines.push(`# ${svc.displayName}`);
    for (const v of vars) {
      if (v.key.trim()) lines.push(`${v.key.trim()}=${v.value}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

interface ServiceTabProps {
  name: string;
}

function ServiceTab({ name }: ServiceTabProps) {
  const { envVars, addEnvVar, updateEnvVar, removeEnvVar } = useWizardStore();
  const vars = envVars[name] ?? [];

  return (
    <div className="space-y-2">
      <ScrollArea className="h-[260px] pr-2">
        <div className="space-y-2">
          {vars.map((v, i) => (
            <div key={i} className="flex gap-2 items-center">
              <Input
                value={v.key}
                onChange={(e) => updateEnvVar(name, i, { key: e.target.value.toUpperCase() })}
                placeholder="KEY"
                className="flex-1 h-8 text-sm font-mono"
              />
              <span className="text-muted-foreground text-xs">=</span>
              <Input
                value={v.value}
                onChange={(e) => updateEnvVar(name, i, { value: e.target.value })}
                placeholder="value"
                className="flex-1 h-8 text-sm font-mono"
              />
              <Button
                size="icon"
                variant="ghost"
                className="h-8 w-8 shrink-0"
                onClick={() => removeEnvVar(name, i)}
              >
                <Trash2 size={12} />
              </Button>
            </div>
          ))}
        </div>
      </ScrollArea>
      <Button size="sm" variant="outline" onClick={() => addEnvVar(name)} className="mt-1">
        <Plus size={12} className="mr-1" />Add Variable
      </Button>
    </div>
  );
}

export default function Step5EnvConfig() {
  const {
    selectedServerId, credential, selectedExternals, envVars,
    setEnvVarsForService, rootPath, nextStep, prevStep,
  } = useWizardStore();
  const { servers } = useServerStore();
  const server = servers.find((s) => s.id === selectedServerId);

  const [saving, setSaving] = useState(false);
  const [saveErr, setSaveErr] = useState("");
  const [saved, setSaved] = useState(false);

  // Auto-fill defaults on first load for each selected service
  useEffect(() => {
    if (!server) return;
    for (const svc of selectedExternals) {
      if (!envVars[svc.name]) {
        const defaults = SERVICE_DEFAULTS[svc.name];
        if (defaults) {
          setEnvVarsForService(svc.name, defaults(server.host));
        } else {
          setEnvVarsForService(svc.name, []);
        }
      }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedExternals.length]);

  const services = selectedExternals.map((s) => ({ name: s.name, displayName: s.displayName }));
  const envContent = buildEnvContent(services, envVars);

  const handleSave = async () => {
    if (!server) return;
    setSaving(true); setSaveErr(""); setSaved(false);
    try {
      await invoke("write_vms_env", {
        host: server.host,
        port: server.port,
        username: server.username,
        authType: server.auth_type,
        credential,
        rootPath,
        content: envContent,
      });
      setSaved(true);
    } catch (e) {
      setSaveErr(String(e));
    } finally {
      setSaving(false);
    }
  };

  if (selectedExternals.length === 0) {
    return (
      <div className="space-y-5">
        <div className="space-y-1">
          <h2 className="text-base font-semibold">Bước 5 — ENV Configuration</h2>
          <p className="text-sm text-muted-foreground">Không có external service nào được chọn ở Bước 4.</p>
        </div>
        <div className="flex justify-between pt-2">
          <Button variant="ghost" onClick={prevStep}>← Quay lại</Button>
          <Button onClick={nextStep}>Tiếp theo →</Button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="space-y-1">
        <h2 className="text-base font-semibold">Bước 5 — ENV Configuration</h2>
        <p className="text-sm text-muted-foreground">
          Cấu hình biến môi trường — lưu vào <code className="font-mono">{rootPath}/vms.env</code>
        </p>
      </div>

      <Tabs defaultValue={selectedExternals[0]?.name}>
        <TabsList className="flex-wrap h-auto gap-1 mb-2">
          {selectedExternals.map((svc) => (
            <TabsTrigger key={svc.name} value={svc.name} className="text-xs">
              {svc.displayName}
            </TabsTrigger>
          ))}
        </TabsList>

        {selectedExternals.map((svc) => (
          <TabsContent key={svc.name} value={svc.name}>
            <ServiceTab name={svc.name} />
          </TabsContent>
        ))}
      </Tabs>

      {/* Actions */}
      <div className="flex items-center gap-3">
        <Dialog>
          <DialogTrigger asChild>
            <Button variant="outline" size="sm">
              <Eye size={13} className="mr-1" />Preview vms.env
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle className="text-sm font-mono">{rootPath}/vms.env</DialogTitle>
            </DialogHeader>
            <ScrollArea className="h-96">
              <pre className="text-xs font-mono p-4 bg-muted rounded-lg whitespace-pre-wrap">
                {envContent || "# (empty)"}
              </pre>
            </ScrollArea>
          </DialogContent>
        </Dialog>

        <Button size="sm" onClick={handleSave} disabled={saving}>
          {saving && <Loader2 size={13} className="mr-1 animate-spin" />}
          {saved ? "✓ Đã lưu vms.env" : "Lưu vms.env lên server"}
        </Button>

        {saveErr && <span className="text-xs text-destructive truncate max-w-xs">{saveErr}</span>}
      </div>

      <div className="flex justify-between pt-2">
        <Button variant="ghost" onClick={prevStep}>← Quay lại</Button>
        <Button onClick={nextStep}>Tiếp theo →</Button>
      </div>
    </div>
  );
}
